title: DDG Tutorial
description: A tutorial on simulating nonlinear behaviors of flexible structures with the discrete differential geometry method
theme: just-the-docs

url: https://zhuonanhao.github.io/DDG_Tutorial_Website

aux_links:
  "View on Github": https://github.com/weicheng-huang-mechanics/DDG_Tutorial

# Enable hierarchical sidebar navigation
just_the_docs:
  collections:
    navigation:
      - order: [Home, Getting Started, Advanced Topics]

search_enabled: true

