title: DDG Tutorial
description: A tutorial on simulating nonlinear behaviors of flexible structures with the discrete differential geometry method
theme: just-the-docs

url: https://zhuonanhao.github.io/DDG_Tutorial_Website

aux_links:
  "View on Github": https://github.com/weicheng-huang-mechanics/DDG_Tutorial

# just_the_docs:
#   collections:
#     navigation:
#       - order: [Home, Getting Started, Documentation, Examples, References]

just_the_docs:
  collections:
    navigation:
      - title: "Home"
        url: "/"
      - title: "Getting Started"
        url: "/getting-started/"
      - title: "Documentation"
        url: "/documentation/"
      - title: "Examples"
        url: "/examples/"
        subnav:
          - title: "Beam Simulations"
            url: "/examples/beam-simulations/"
          - title: "Rod Simulations"
            url: "/examples/rod-simulations/"
          - title: "Plate Simulations"
            url: "/examples/plate-simulations/"
      - title: "References"
        url: "/references/"

        search_enabled: true