title: DDG Tutorial
description: A tutorial on simulating nonlinear behaviors of flexible structures with the discrete differential geometry method
theme: just-the-docs

url: https://zhuonanhao.github.io/DDG_Tutorial_Website

aux_links:
  "View on Github": https://github.com/weicheng-huang-mechanics/DDG_Tutorial

# just_the_docs:
#   collections:
#     navigation:
#       - order: [Home, Getting Started, Documentation, Examples, References]

just_the_docs:
  collections:
    navigation:
      - title: "Home"
        url: "/"
      - title: "Getting Started"
        url: "/getting-started/"
      - title: "Documentation"
        url: "/documentation/"
      - title: "Examples"
        url: "/examples/"
        subnav:
          - title: "2D Curve Simulations"
            url: "/examples/2d_curve/"
          - title: "2D Surface Simulations"
            url: "/examples/2d_surface/"
          - title: "3D Curve Simulations"
            url: "/examples/3d_curve/"
          - title: "3D Surface Simulations"
            url: "/examples/3d_surface/"
      - title: "References"
        url: "/references/"

search_enabled: true

footer_content: "custom"

head:
  - '<script type="text/javascript" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>'